### PR TITLE
CI: also test with only needed packages loaded

### PR DESCRIPTION
**Pull request by fingolfin**
... to verify the optional depenendcies really are optional

### CODE REVIEW

**Comment by fingolfin** [comment]
It seems that at the very least the dependency on IO is not really optional and should be moved back to `NeededPackages`. Or else the code should be rewritten to use `Process` instead of `IO_Popen3`

**Review by margollo — APPROVED** [review]

**Comment by fingolfin** [comment]
it still fails but now due to normalizinterface...

**Comment by margollo** [comment]
It seems to me it first fails because it did not load CTbLib, maybe this should also always be loaded

**Comment by margollo** [comment]
I did this change and if I understand correctly the tests just finished successfully. There are syntax warnings, but these are probably unavoidable if commands are included from packages which are not required.

**Pull request merged**
