### PR TITLE
Remove use of deprecated @EndSection

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by margollo** [comment]
@EndSection have been removed in release 3.5.

**Comment by alex-konovalov** [comment]
This is still not in the master branch.

**Comment by fingolfin** [comment]
The repository also only contains version 3.4. Are you perhaps developing the package outside the repository? That would be bad :-(

**Comment by fingolfin** [comment]
Indeed, it seems you manually uploaded a release 3.5 tarball, but did not update the repository, did not update the website, and did not incorporate several changes that were made since 3.4 to this git repository.

**Comment by margollo** [comment]
Hi Alex and Max,

thank you a lot for sorting it out. We somehow thought putting it in releases would be enough. Next time we will do it properly.

All the best
Leo

**Comment by alex-konovalov** [comment]
@margollo Ok! If you need a recap of using Git and GitHub, please ask me in 2020!

**Pull request closed without merging**
